[build-system]
requires = ["setuptools >= 61.0", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "SoA"
dynamic = ["version"]

[tool.setuptools_scm]
version_file = "PopSynthesis/_version.py"