####################################################################
# PopulationSim Properties
####################################################################


# Algorithm/Software Configuration
# ------------------------------------------------------------------
INTEGERIZE_WITH_BACKSTOPPED_CONTROLS: True
SUB_BALANCE_WITH_FLOAT_SEED_WEIGHTS: False
GROUP_BY_INCIDENCE_SIGNATURE: True
USE_SIMUL_INTEGERIZER: True
USE_CVXPY: False
max_expansion_factor: 30


# Geographic Settings
# ------------------------------------------------------------------
geographies: [SA3, SA1]
seed_geography: SA3


# Tracing
# ------------------------------------------------------------------


  
# Data Directory
# ------------------------------------------------------------------
data_dir: data


# Input Data Tables
# ------------------------------------------------------------------
# input_pre_processor input_table_list
input_table_list:
  - tablename: households
    filename : H_sample.csv
    index_col: hh_id
    rename_columns:
      # not sure what SERIALNO is, but it is not unique
      #SERIALNO: hh_id
      hh_num: hh_id
  - tablename: persons
    # expression_filename: seed_persons_expressions.csv
    filename : P_sample.csv
    rename_columns:
      hh_num: hh_id
  - tablename: geo_cross_walk
    filename : geo_cross.csv
  - tablename: SA3_control_data
    filename : census_SA3.csv
  - tablename: SA1_control_data
    filename : census_SA1.csv


# Reserved Column Names
# ------------------------------------------------------------------
household_weight_col: wdhhwgt_sa3
household_id_col: hh_id
total_hh_control: num_hh


# Control Specification File Name
# ------------------------------------------------------------------
control_file_name: controls.csv


# Output Tables
# ------------------------------------------------------------------
# output_tables can specify either a list of output tables to include or to skip
# if neither is specified, then no tables will be written

output_tables:
  action: include
  tables:
    - summary_SA1
    - expanded_household_ids


# Synthetic Population Output Specification
# ------------------------------------------------------------------
#

output_synthetic_population:
  household_id: household_id
  households:
    filename: synthetic_households.csv
    columns:
      - totalvehs
      - hhsize
  persons:
    filename: synthetic_persons.csv
    columns:
      - sex
      - persinc


# Model steps for base mode
# ------------------------------------------------------------------
models:
    - input_pre_processor
    - setup_data_structures
    - initial_seed_balancing
    - meta_control_factoring
    - final_seed_balancing
    - integerize_final_seed_weights
    - sub_balancing.geography=SA1
    - expand_households
    - write_data_dictionary
    - summarize
    - write_tables
    - write_synthetic_population

resume_after:
